export const projects = [
  // All Projects
  {
    slug: "volkswagenproject",
    title: "Volkswagen Project",
    images: [
      "/assets/images/allprojects/volkswagen/volkswagen1.webp",
      "/assets/images/allprojects/volkswagen/volkswagen2.webp",
    ],
    video: "/assets/videos/video1.mp4",
    body: [
      "A comprehensive branding project for Volkswagen, focusing on modern automotive design principles.",
      "Created visual identity elements including logos, color schemes, and marketing materials that reflect Volkswagen's heritage while embracing contemporary design trends.",
      "The project involved extensive research into automotive industry standards and consumer preferences.",
    ],
    tags: ["Graphic design", "Branding", "Automotive"],
    dropcap: "V",
    behanceEmbedUrl: undefined,
  },
  {
    slug: "chromemagazine",
    title: "Chrome Magazine",
    image: "/assets/images/sjonlee.jpeg",
    body: [
      "Editorial design project for Chrome Magazine, a cutting-edge publication focused on technology and innovation.",
      "Designed layouts, typography, and visual elements that capture the dynamic nature of the tech industry.",
      "Collaborated with writers and photographers to create compelling visual narratives.",
    ],
    tags: ["Magazine", "Editorial", "Typography"],
    dropcap: "C",
  },
  {
    slug: "rinkitoucreativeagency",
    title: "Rinkitou Creative Agency",
    image: "/assets/images/sjonlee.jpeg",
    body: [
      "Founded and designed the complete brand identity for Rinkitou Creative Agency.",
      "Developed a comprehensive visual system including logo design, color palette, typography, and brand guidelines.",
      "Created marketing materials, website design, and business collateral that established the agency's professional presence.",
    ],
    tags: ["Agency", "Branding", "Entrepreneurship"],
    dropcap: "R",
  },
  {
    slug: "popupstoreberlin",
    title: "Pop Up Store Berlin",
    image: "/assets/images/sjonlee.jpeg",
    body: [
      "Thrilled to share that my very first pop-up store in collaboration with ObeyArtSpace was a huge success!",
      "Over 280 people attended — all fresh faces, young creatives, and amazing energy throughout the event. The space was filled with curiosity, community, and great vibes.",
      "A huge thank you to ObeyArtSpace for believing in the idea, and to my creative agency and everyone involved in making this happen — from the projects to the event itself. ❤️",
      "See you next year. Bigger, louder, weirder.",
    ],
    tags: ["Graphic design", "Posters", "Clothing"],
    dropcap: "T",
  },
  {
    slug: "clothingdesign",
    title: "Clothing Design",
    image: "/assets/images/placeholder.png",
    body: ["Clothing Design content."],
    tags: ["Clothing", "Fashion"],
    dropcap: "C",
  },
  {
    slug: "3ddesign",
    title: "3D design",
    image: "/assets/images/placeholder.png",
    body: ["3D design content."],
    tags: ["3D", "Design"],
    dropcap: "3",
  },
  // Hidden
  {
    slug: "youngerme",
    title: "Younger me",
    image: "/assets/images/sjonlee.jpeg",
    body: ["Younger me project content."],
    tags: ["Hidden", "Archive"],
    dropcap: "Y",
  },
  {
    slug: "firstportfolio",
    title: "FirstPortfolio",
    image: "/assets/images/sjonlee.jpeg",
    body: ["FirstPortfolio project content."],
    tags: ["Hidden", "Archive"],
    dropcap: "F",
  },
  {
    slug: "olddesigns",
    title: "Old Designs",
    image: "/assets/images/sjonlee.jpeg",
    body: ["Old Designs project content."],
    tags: ["Hidden", "Archive"],
    dropcap: "O",
  },
  // Untitled
  {
    slug: "moodboard1",
    title: "Moodboard 1",
    image: "/assets/images/sjonlee.jpeg",
    body: ["Moodboard 1 project content."],
    tags: ["Untitled"],
    dropcap: "M",
  },
  {
    slug: "untitled1",
    title: "Untitled 1",
    image: "/assets/images/sjonlee.jpeg",
    body: ["Untitled 1 project content."],
    tags: ["Untitled"],
    dropcap: "U",
  },
  {
    slug: "untitled2",
    title: "Untitled 2",
    image: "/assets/images/sjonlee.jpeg",
    body: ["Untitled 2 project content."],
    tags: ["Untitled"],
    dropcap: "U",
  },
  // Coming soon
  {
    slug: "rinkitounewcollection",
    title: "rinkitou® new collection",
    image: "/assets/images/sjonlee.jpeg",
    body: ["rinkitou® new collection project content."],
    tags: ["Coming soon"],
    dropcap: "R",
  },
  {
    slug: "lettertofutureme",
    title: "Letter to future me",
    image: "/assets/images/sjonlee.jpeg",
    body: ["Letter to future me project content."],
    tags: ["Coming soon"],
    dropcap: "L",
  },
];
