export const projects = [
  // All Projects
  {
    slug: "volkswagenproject",
    title: "Volkswagen Project",
    images: [
      "/assets/images/allprojects/volkswagen/volkswagen1.webp",
      "/assets/images/allprojects/volkswagen/volkswagen2.webp",
    ],
    video: "/assets/videos/video1.mp4",
    body: [
      "comprehensive branding project for Volkswagen, focusing on modern automotive design principles.",
      "Created visual identity elements including logos, color schemes, and marketing materials that reflect Volkswagen's heritage while embracing contemporary design trends.",
      "The project involved extensive research into automotive industry standards and consumer preferences.",
    ],
    tags: ["UX/UI", "Graphic design", "Branding", "Automotive", "Pitching"],
    dropcap: "A",
  },
  {
    slug: "chromemagazine",
    title: "Chrome Magazine",
    images: [
      "/assets/images/allprojects/chrome/chrome1.webp",
      "/assets/images/allprojects/chrome/chrome2.webp",
      "/assets/images/allprojects/chrome/chrome3.webp",
      "/assets/images/allprojects/chrome/chrome4.webp",
      "/assets/images/allprojects/chrome/chrome5.webp",
      "/assets/images/allprojects/chrome/chrome6.webp",
      "/assets/images/allprojects/chrome/chrome7.webp",
      "/assets/images/allprojects/chrome/chrome8.webp",
      "/assets/images/allprojects/chrome/chrome9.webp",
      "/assets/images/allprojects/chrome/chrome10.webp",
      "/assets/images/allprojects/chrome/chrome11.webp",
      "/assets/images/allprojects/chrome/chrome12.webp",
      "/assets/images/allprojects/chrome/chrome13.webp",
      "/assets/images/allprojects/chrome/chrome14.webp",
      "/assets/images/allprojects/chrome/chrome15.webp",
      "/assets/images/allprojects/chrome/chrome16.webp",
      "/assets/images/allprojects/chrome/chrome17.webp",
      "/assets/images/allprojects/chrome/chrome18.webp",
      "/assets/images/allprojects/chrome/chrome19.webp",
      "/assets/images/allprojects/chrome/chrome20.webp",
      "/assets/images/allprojects/chrome/chrome21.webp",
      "/assets/images/allprojects/chrome/chrome22.webp",
      "/assets/images/allprojects/chrome/chrome23.webp",
      "/assets/images/allprojects/chrome/chrome24.webp",
      "/assets/images/allprojects/chrome/chrome25.webp",
      "/assets/images/allprojects/chrome/chrome26.webp",
    ],
    body: [
      "nternship at Chrome Magazine, a Berlin-based publication focused on technology and innovation. During my time there, I met inspiring creatives, expanded my network, and gained invaluable hands-on experience.",
      "Worked on designing layouts, typography, and visual elements that reflected the magazine's dynamic style.",
      "Collaborated closely with writers and photographers to create engaging visual stories and bring ideas to life.",
    ],
    tags: [
      "Magazine",
      "Editing",
      "Typography",
      "3D design",
      "Internship",
      "Networking",
    ],
    dropcap: "I",
  },
  {
    slug: "rinkitoucreativeagency",
    title: "Rinkitou Creative Agency",
    images: ["/assets/images/allprojects/rinkitou/rinkitou.webp"],
    body: [
      "ounded and designed the complete brand identity for Rinkitou Creative Agency.",
      "Developed a comprehensive visual system including logo design, color palette, typography, and brand guidelines.",
      "Created marketing materials, website design, and business collateral that established the agency's professional presence.",
    ],
    tags: ["Agency", "Branding", "Entrepreneurship", "Visual identity"],
    dropcap: "F",
  },
  {
    slug: "popupstoreberlin",
    title: "Pop Up Store Berlin",
    images: ["/assets/images/allprojects/obey/obeyxrinkitou.webp"],
    body: [
      "hrilled to share that my very first pop-up store in collaboration with ObeyArtSpace was a huge success!",
      "Over 280 people attended — all fresh faces, young creatives, and amazing energy throughout the event. The space was filled with curiosity, community, and great vibes.",
      "A huge thank you to ObeyArtSpace for believing in the idea, and to my creative agency and everyone involved in making this happen — from the projects to the event itself. ❤️",
      "See you next year. Bigger, louder, weirder.",
    ],
    tags: ["Graphic design", "Posters", "Clothing"],
    dropcap: "T",
  },
  {
    slug: "3ddesign",
    title: "3D design",
    images: ["/assets/images/allprojects/3d/3d_1.webp"],
    body: [
      "D design has always fascinated me because I love creating in a three-dimensional space. While I’ve never been strong at sketching, visualizing ideas in 3D always made more sense to me.",
      "This project was also a great way to deepen my understanding of 3D and explore how to implement it in coding a skill I’m excited to continue developing.",
    ],
    tags: ["3D", "Design", "THREE.JS", "Coding", "WebGL"],
    dropcap: "3",
  },
  // Hidden
  {
    slug: "youngerme",
    title: "Younger me",
    images: [
      "/assets/images/sjonlee6.jpeg",
      "/assets/images/sjonlee18.jpeg",
      "/assets/images/sjonlee10.jpeg",
      "/assets/images/sjonlee21.jpeg",
    ],
    body: [
      "ounger me, a little album of who I was to who I am now. Lovely photos from the past to my current state of life. Always thankful for my parents who have put me here in this world and gave all their best to help me out and gave me the things I needed that they couldn't have when they were young.",
    ],
    tags: ["Hidden", "Archive"],
    dropcap: "Y",
  },
  {
    slug: "firstportfolio",
    title: "FirstPortfolio",
    images: [
      "/assets/images/allprojects/portfolio/firstportfolio.webp"
    ],
    body: ["irstPortfolio that i created around 2022 - 2023. This was my vibe in 2022 of designing I didn't liked coding then. But now I do. Experimental style, also trying to be unique as well. It's nice because every year every chapter shows the process of who I am and you can see that in my evolution tho."],
    tags: ["Hidden", "Archive"],
    dropcap: "F",
  },
  // Untitled

  // {
  //   slug: "untitled1",
  //   title: "Untitled 1",
  //   images: ["/assets/images/folder.svg"],
  //   body: ["Untitled 1"],
  //   tags: ["Untitled"],
  //   dropcap: "U",
  // },
  // {
  //   slug: "untitled2",
  //   title: "Untitled 2",
  //   images: ["/assets/images/folder.svg"],
  //   body: ["Untitled 2"],
  //   tags: ["Untitled"],
  //   dropcap: "U",
  // },
  // Coming soon
  {
    slug: "lettertofutureme",
    title: "Letter to future me",
    image: "/assets/images/sjonlee.jpeg",
    body: ["etter to future me."],
    tags: ["Coming soon"],
    dropcap: "L",
  },
];
